[package]
name = "cii"
version = "0.1.0"
edition = "2024"

[dependencies]
termion = "1.5"
nix = "0.23"
chrono = "0.4"
tokio = { version = "1", features = ["full"] }

[[bin]]
name = "cii"
path = "cii/src/main.rs"
